### ISSUE TITLE
Issues for Course Management App by Isabel 

### ISSUE THREAD

**Issue by IsabelCarvalho** [Higino/CourseManagementApp#1]
1 - rename button "Import Data" to "Home"
2 - put "Enrollments" in second place 
3 - allow for bigger pre-reqs file (attached)
[report1622022889625.xls](https://github.com/Higino/CourseManagementApp/files/6545734/report1622022889625.xls)

**Comment by Higino** [comment]
In point number 2 what do you mean by putting Enrolments in second place, are you talking about the menu?

**Comment by Higino** [comment]
Implemented and released to main branch. Corrections available in the app zip download link
